### ISSUE TITLE
Internal Server Error in planetary/earth/imagery api

### ISSUE THREAD

**Issue by medakk** [nasa/api-docs#102]
I'm seeing internal server errors when I query for images in 2018, or late 2017 with https://api.nasa.gov/planetary/earth/imagery/?lon=77.593675&lat=12.972172&date=2018-01-01&api_key=DEMO_KEY

```
{
  "msg": "Internal Service Error", 
  "service_version": "v1"
}
```

**Comment by mbparis** [comment]
Was a solution ever found for this?

**Comment by medakk** [comment]
No, I never found a solution for it. Query for the previous years works though.

**Comment by twilco** [comment]
@jasonduley - any word on this?  Between this issue and another one opened by @medakk, it seems like these pretty major problems are just left to be unresolved.  It's a shame because NASA's APIs seem quite neat.

**Comment by html1011** [comment]
I’ve been recently recieving the same error- though only in some cases. The day before, I sent a request for all dates May 29, 2017 to December 31, 2017. Today, I made the a request for dates January 1, 2017 through December 31, 2017- and I found something strange. I was using a completely new API Token, on a different network, and all of the dates before May 29 worked. But from May 29 2017 to December 31 2017, I was recieving an internal service error as well.

**Comment by gafortiby** [comment]
I also have this issue, and it seems that NOT using a data pulls the OLDEST image instead of the NEWEST images as the documentation says. Now that it's 2019, it seems all requests with 2019 fails. :(

**Comment by JustinGOSSES** [comment]
This API is broken for certain date ranges. We are attempted to find/contact a current API owner. In the mean time, this service is basically a wrapper around google earth engine, so you can use it. A downside is the more complex interface.

**Comment by nehemias-bit** [comment]
How zoomed in will the returned image? Is the quality good enough for me to see house for example?

**Comment by JustinGOSSES** [comment]
@nehemias-bit you can try the API for the 2017 date range and change the lat/long to be your house to see the zoom level.

**Comment by Tomas527** [comment]
Jest uploaded a demonstration video of an IOS app I wrote using this API. 
Soon everyone with an iPhone will have this amazing tool for earth exploring.

https://www.linkedin.com/posts/tomer-abady-766ba2193_a-demonstration-of-earth-rewinder-the-first-activity-6624342427408965632-6F5U

**Comment by JustinGOSSES** [comment]
@Tomas527 thanks for sharing. Love that you built your first IOS app with NASA API data, please share in this issue thread. https://github.com/nasa/api-docs/issues/125  We're trying to build up a list of examples like this!

**Comment by JustinGOSSES** [comment]
original issue is fixed so will close
