### ISSUE TITLE
Access-Control-Allow-Origin Header

### ISSUE THREAD

**Issue by JacobTDC** [nasa/api-docs#103]
Would it be at all possible to add the `Access-Control-Allow-Origin: "*"` header to the server response (specifically for the mars-photos api)? I'm asking this because I'm working on a client-side HTML utility that allows searching for rover photos after inputing an API key, and it only works in Incognito Mode in certain browsers on certain devices.

**Comment by jasonduley** [comment]
please try it again ...

**Comment by JacobTDC** [comment]
It occasionally works.

**Comment by JacobTDC** [comment]
Sorry, this issue was fixed awhile back, I forgot to close it! XD
