### ISSUE TITLE
https://api.nasa.gov/contact/ results in a 404

### ISSUE THREAD

**Issue by twilco** [nasa/api-docs#106]
Messing around on the API documentation page, I managed to catch the DEMO_KEY in a state of being over the rate limit.  The message when this happens looks like this:

OVER_RATE_LIMIT
You have exceeded your rate limit. Try again later or contact us at https://api.nasa.gov/contact/ for assistance

However, https://api.nasa.gov/contact/ results in this error:

```
404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.
```

**Comment by JustinGOSSES** [comment]
Took off the link
