### ISSUE TITLE
No CORS for Techport API

### ISSUE THREAD

**Issue by amaust82** [nasa/api-docs#107]
I'm getting a CORS errror on the Techport API with a message of: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by jasonduley** [comment]
please try it again

**Comment by amaust82** [comment]
Looks great! Thank you for the quick update.

**Comment by amaust82** [comment]
Oops, spoke too soon. Looks like that broke the updatedSince param on projects.

https://api.nasa.gov/techport/api/projects?updatedSince2018-07-01&api_key=[redacted]
