### ISSUE TITLE
One of the EPIC demo links results in 500 error

### ISSUE THREAD

**Issue by JustinGOSSES** [nasa/api-docs#111]
https://api.nasa.gov/EPIC/archive/enhanced/2016/12/04/png/epic_RBG_20161204003633.png?api_key=DEMO_KEY

One of the EPIC demo links results in 404 error

**Comment by hemangshah** [comment]
Actually, there's are few which isn't working and throwing error.

**Comment by hemangshah** [comment]
If you're from dev team or contributor please check this out, https://github.com/nasa/api-docs/issues/109 - This guy have already fixed this issue.

**Comment by JustinGOSSES** [comment]
I'm going through and finding all the dead api.nasa.gov links. I don't have write access to the separate repo that impacts #109 but I've flagged it to at least one person who I believe does.

**Comment by hemangshah** [comment]
Thanks @JustinGOSSES, this will help. 👍🏼

**Comment by JustinGOSSES** [comment]
fixed & merged via https://github.com/nasa/apod-api/pull/16

**Comment by hemangshah** [comment]
@JustinGOSSES can you please share EPIC site link where we can see this info?

**Comment by JustinGOSSES** [comment]
https://epic.gsfc.nasa.gov/about/api
