### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by dkinslert** [nasa/api-docs#116]
https://api.nasa.gov/patents/content?query=temperature&limit=5&api_key=DEMO_KEY

![Captura de pantalla de 2019-09-18 08-13-32](https://user-images.githubusercontent.com/4423678/65147612-834ece80-d9ec-11e9-8e7f-72b3367a5c53.png)
![Internal Server Error](https://user-images.githubusercontent.com/4423678/65147743-c315b600-d9ec-11e9-879f-fbb3506f1dfb.png)

**Comment by JustinGOSSES** [comment]
Looking into this. Added "NOTE: THIS IS DOWN CURRENTLY:" to the API description. Thank you.

**Comment by dkinslert** [comment]
it would be better if I would be disabled, thank you too.

**Comment by JustinGOSSES** [comment]
patents API replaced with techTransfer API
