### ISSUE TITLE
No Earth data for certain latitudes and longitudes

### ISSUE THREAD

**Issue by ARtheboss** [nasa/api-docs#117]
I live in Singapore, where @ 1.3521° N, 103.8198° E. However, when I search for something like this: https://api.nasa.gov/planetary/earth/imagery/lon=1.3521&lat=103.8198&api_key=DEMO_KEY, it keeps giving internal server errors. Am I doing something wrong? I just want pictures of my house.

**Comment by JustinGOSSES** [comment]
The owner of this API has left NASA and the API's functionality has decreased over time, so we're in the process of building a replacement. It is on the 'to-do' list for the next sprint. 

In the meantime, https://developers.google.com/earth-engine/ has similar functionality but a little more complex API user experience.

**Comment by JustinGOSSES** [comment]
Anyone have a very simple earth imagery code that could be packaged as an API?

**Comment by JustinGOSSES** [comment]
API is now fixed
