### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by MDStebel** [nasa/api-docs#130]
The Imagery API is returning an error:
Example: https://api.nasa.gov/planetary/earth/imagery/?lon=100.75&lat=1.5&date=2014-02-01&cloud_score=True&api_key=DEMO_KEY
Returns:
<img width="476" alt="Screen Shot 2020-03-31 at 1 15 36 PM" src="https://user-images.githubusercontent.com/12930579/78055582-bf76ca80-7351-11ea-8e45-426de71c77c0.png">

Will this be fixed?

**Comment by JustinGOSSES** [comment]
Updated the api.nasa.gov description for that API with: 

> THIS API IS CURRENTLY DOWN DUE TO THE DEPRECIATION OF ANOTHER API IT DEPENDED ON! We are currently investigating the best replacement. In the meantime, NASA's Earth Science Devision also has a variety of Earth imagery APIs for developers, which you can find out about in the Earthdata Developer Portal. Specifically, the GIBS (Global Imagery Browse Services) API may be of interest. The Google Earth Engine API is another option that performs similarly to the API that was in this location and serves from the same datasets. We apologize for the inconvenience.

**Comment by JustinGOSSES** [comment]
Thanks for flagging @MDStebel

**Comment by MDStebel** [comment]
Thanks!




 <https://www.facebook.com/MichaelStebelConsulting/>		 <https://www.linkedin.com/in/michaelstebel/>	 		
Michael Stebel
Management Consultant ∙ SaaS Guru ∙ Indie App Developer
MICHAEL STEBEL CONSULTING

561.252.1081‬ <tel:(561)%20252-1081>
	michael@michaelstebelconsulting.com <mailto:michael@michaelstebelconsulting.com>
	michaelstebelconsulting.com <https://www.michaelstebelconsulting.com/>

**Comment by JustinGOSSES** [comment]
Earth imagery API is back up. It doesn't have the cloud filtering functionality any more. If this is very important to you, I'd advise using one of the other imagery APIs mentioned in the description of the earth imagery api. 

Closing this issue as the API is back up.
