### ISSUE TITLE
CORS issue with TechTransfer API

### ISSUE THREAD

**Issue by dengoloborodko** [nasa/api-docs#132]
I've sent a request to the TechTransfer API, using the following URL:

https://api.nasa.gov/techtransfer/patent/?engine&api_key=myKey

And received the CORS error:

Access to fetch at 'https://api.nasa.gov/techtransfer/patent/engine&api_key=myKey' from origin 'mySite' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://technology-api.ndc.nasa.gov' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Is it possible to enable CORS for this API, so I can access them for my project?

**Comment by JustinGOSSES** [comment]
Should be fixed now. Works for me. 

I'll wait until we have your response before we close this issue.

**Comment by dengoloborodko** [comment]
> Should be fixed now. Works for me.
> 
> I'll wait until we have your response before we close this issue.

Yes, now works for me too. Thank you so much for the fast response!

**Comment by JustinGOSSES** [comment]
Sometimes I'm lucky and things are easy 😄
