### ISSUE TITLE
Earth is not functional. 

### ISSUE THREAD

**Issue by joejoe909** [nasa/api-docs#134]
Hello,
      Earth doesn't seem functional. Please see these links as they're not working correctly. 

These are you test links that won't work. They don't work with my api key either. 
https://api.nasa.gov/planetary/earth/imagery?lon=100.75&lat=1.5&date=2014-02-01&api_key=DEMO_KEY
https://api.nasa.gov/planetary/earth/assets?lon=-95.33&lat=29.78&date=2018-01-01&&dim=0.10&api_key=DEMO_KEY

**Comment by JustinGOSSES** [comment]
A security update caused some issues on the server. These links work now. Thank you

**Comment by joejoe909** [comment]
Thanks Justin, while the imagery works the assets link does not. FYI. See my links above.

**Comment by JustinGOSSES** [comment]
Thanks again. I must have only tested the imagery endpoint. Both should be working now.
