### ISSUE TITLE
Earth landsat 

### ISSUE THREAD

**Issue by Iinguistics** [nasa/api-docs#135]
I am using chrome version: 86.0.4240.183
The example query throw a 500 server error
My calls were working about 2 weeks ago perfectly fine, then I started getting a cors error,
so I set up Access-Control-Allow-Origin: *  & got the 500 server error. 
Is this Earth landsat API taken offline?

**Comment by JustinGOSSES** [comment]
There was a security update that broke things. Should be fixed now
