### ISSUE TITLE
./neo/rest/v1/feed response model

### ISSUE THREAD

**Issue by ghost** [nasa/api-docs#137]
Good morning,
i am working on this
https://github.com/mattiapontonio/asteroids/blob/4f4d7e80e5e841a4b6ab7415e8ddf6384289238b/components/ScatterPlot.vue

and as in other projects I have had problems with how the body of the response is modeled
https://api.nasa.gov/neo/rest/v1/feed?start_date=START_DATE&end_date=END_DATE&api_key=API_KEY

- I would first need a specific endpoint for a specific date because in some contexts I don't have two dates. 
- Also in the current response the arrays of objects are assigned to keys corresponding to the date. 
- This makes it difficult to map the results for some edge cases. 
- It would be ideal in my opinion to provide an object response which contains an items key which is guaranteed to be an array. 
- Or directly the array itself ...
- The most problematic thing is the keys because you cannot map if the date is undefined.

**Comment by ghost** [comment]
Hello, Is the right repo? Can someone address this?

**Comment by JustinGOSSES** [comment]
This redo doesn't hold any of the APIs themselves as stated in the README.

 If you go to the page for NEO API (if not linked in api.nasa.gov a Google search should bring it up), you can try to find appropriate page / contacts for the near earth object API.

**Comment by JustinGOSSES** [comment]
If I understand what you're saying about the problem of "undefined", your best bet is to have your code test for that condition itself as a precaution. It can be a bit tricky but probably your fastest way forward.

Changing the response structure of an API already used by many is a big ask.

Given we can't help you here directly, I'm going to close this issue. Best of luck.

**Comment by dgreenfield0** [comment]
Hey @mattiapontonio - I maintain the NeoWs Asteroid API - Feel free to email: spacerocksapps@gmail.com

Thanks @JustinGOSSES
