### ISSUE TITLE
I don't like this response

### ISSUE THREAD

**Issue by ghost** [nasa/api-docs#139]
If I understand what you're saying about the problem of "undefined", your best bet is to have your code test for that condition itself as a precaution. It can be a bit tricky but probably your fastest way forward.

Changing the response structure of an API already used by many is a big ask.

Given we can't help you here directly, I'm going to close this issue. Best of luck.

_Originally posted by @JustinGOSSES in https://github.com/nasa/api-docs/issues/137#issuecomment-736225662_

Things changhes.
Anyway this Is Just issues.

**Comment by ghost** [comment]
Maybe We (of course You but We as developers) can use 
https://en.wikipedia.org/wiki/HATEOAS

Inside the `Near-earth-objests` _collection rappresented like an object_ in order to force the `date` to be exposed as a entity...

Or more good maybe keep `asteroids` like an entity and expose the filtering feature...

I need to 🤔💭
Feel free to expose your impressions.

**Comment by JustinGOSSES** [comment]
The admins here don't control the Near Earth Objects API as addressed elsewhere, if someone else stumbles upon this issues, you can reach them at https://github.com/SpaceRocks/ & spacerocksapps@gmail.com

**Comment by ghost** [comment]
@JustinGOSSES thanks.
The API level could be open sourced in some way in order to discuss about the endpoints and the responses.
I didn't find the right repository for this, all seems about documentation, this Is a "server issue".
