### ISSUE TITLE
Neo service application error

### ISSUE THREAD

**Issue by mmd44** [nasa/api-docs#140]
https://api.nasa.gov/neo/rest/v1/neo/browse?api_key=DEMO_KEY

This service is returning an application error:
503 Service Unavailable
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command

**Comment by dgreenfield0** [comment]
Hey @mmd44  

We are looking into the issue and should have the service back soon.

Thanks,
~SpaceRocksTeam

**Comment by dgreenfield0** [comment]
Hey @mmd44, 

NeoWs is back up. Please let us know if you have any more issues.

The error was related to an unexpected infrastructure outage, which has been resolved.


Thanks
~SpaceRocksTeam
