### ISSUE TITLE
Alert appears on slow internet connection

### ISSUE THREAD

**Issue by HilaryDev** [nasa/api-docs#150]
## Description of the problem
  
  When loading the webpage (https://api.nasa.gov/) with slow to intermittent internet connection (around 10KB per second), an alert appears that says `getJSON request failed! error`. Not in the user interface, but rather an alert that seems invoked by JavaScript, like `alert('getJSON request failed! error')`.
  
This does not happen when the internet connection is fast (500+ MB per second)
  
  I am _guessing_ that showing this alert is unintentional? I understand that most people viewing the catalog page will probably be developers, but I'm guessing from the alert message that it's actually something left accidentally after a debugging session.
  
  Having the alert pop up like that also hurts accessibility, since screen readers lose focus (due to the `onblur` handler in JavaScript's default `alert` function).
  
  
## What did I expect to happen?
  
  When visiting the webpage with a slow internet connection, that alert shouldn't appear. At least, if the site fails to load because of how slow a user's internet connection is, it should do so silently - not suddenly pop an alert about it.
  
  
## System Information
  
- **Browser:** Google Chrome version 91.0.4472.114 (Official Build) (32-bit)
- **Operating System:** Windows 8.1 Pro
- **PC System Type:** 32-bit operating-system, x64-based processor
- I accessed the website using my phone as a hotspot (ie. using my phone's WiFi), if that matters.
  
  
## Where I think the issue lies
  
  Searching through the source code, the [APILoader](https://github.com/nasa/api-docs/edit/gh-pages/assets/js/APILoader.js) file _seems_ to be the culprit, so I have opened a pull request ([#151](https://github.com/nasa/api-docs/pull/151)) that solves the issue.
  
If the alert is there on purpose, then I'm sorry! Let me know and I'll close this issue (and the related pull request) ASAP.

**Comment by JustinGOSSES** [comment]
Seems reasonable. Thanks for the pull request. It has been merged.
