### ISSUE TITLE
CORS error with SSD/CNEOS CAD API fetch. 

### ISSUE THREAD

**Issue by FBascou** [nasa/api-docs#156]
Hello,

I am getting CORS error from the following url: 
https://ssd-api.jpl.nasa.gov/cad.api?dist-max=0.05&fullname=true&date-min=2021-11-04&date-max=2021-12-31&sort=date'

The url above was working a 2-3 months ago and now it is being blocked by CORS policy. 

Hope that this can be changed please.

Thanks! :)

**Comment by JustinGOSSES** [comment]
1. The URL works for me. 
2. The admins of this repo don't control that API or have any insight into it. api.nasa.gov is a passthrough service. It doesn't host the APIs themselves. 

Suggest you try the contact email listed on that specific API page: https://ssd-api.jpl.nasa.gov/about/ 

As this isn't related to api.nasa.gov , will close this issue.
