### ISSUE TITLE
Broken Links to SSCWeb

### ISSUE THREAD

**Issue by brooksvb** [nasa/api-docs#173]
The links to [Satellite Situation Center Web (SSCWeb) service](https://sscweb.sci.gsfc.nasa.gov/WebServices/REST/) are broken, giving "Name not resolved / IP address not found" errors.

Both the link with text "Satellite Situation Center Web (SSCWeb) service" and "visit this page." are broken.

**Comment by KhurramJalil** [comment]
Both the broken links will get fixed once the following PR #199 gets reviewed/approved/merged into the live branch.
