### ISSUE TITLE
Reconsider the 3 column layout?

### ISSUE THREAD

**Issue by gbinal** [nasa/api-docs#2]
It's a bit distracting.

**Comment by gbinal** [comment]
One thing though, could the example sections on the right was horizontally lined up with the section on the left

**Comment by danhammer** [comment]
@jasonduley thanks for taking this on.  the current layout supports the gutter examples.  We should probably just scrap the three-column layout in favor of your JSFiddles idea, build directly into the docs (as opposed to putting in the third-column).

**Comment by danhammer** [comment]
any updates on this issue, @jasonduley?  should I close this issue or are you planning on adding the JSFiddle stuff?

**Comment by jasonduley** [comment]
keep it open.  I am still planning on adding this feature
