### ISSUE TITLE
Consider interactive documentation

### ISSUE THREAD

**Issue by gbinal** [nasa/api-docs#20]

**Comment by jasonduley** [comment]
Gray, excellent feedback.  Can you send me an example of someone that has done this well?  thanks.

**Comment by danhammer** [comment]
[this one](https://www.twilio.com/docs/howto/walkthrough/two-factor-authentication/python/flask#1) is what the twilio guy pointed out.

**Comment by gbinal** [comment]
Here you go - http://18f.github.io/API-All-the-X/pages/api_release_kit#interactive-sample
