### ISSUE TITLE
Change the contact-us link in the api key signup 

### ISSUE THREAD

**Issue by gbinal** [nasa/api-docs#33]
At http://nasa.github.io/api-docs/#apply-for-an-api-key, after filling out the form and requesting the key, the default language  includes a contact us link that goes to `https://api.data.gov/contact/`.  It would be better to have that link to `https://github.com/nasa/api-docs/issues` or the NASA API team's preferred contact mechanism.  

It looks like this is hard baked into `https://api.data.gov/static/javascripts/signup_embed.js`, so it may be that the api.data.gov team needs to create an agency-specfic version of the file to do this.  

@gui - any thoughts?

**Comment by gbinal** [comment]
![screen shot 2015-04-27 at 11 50 58 am](https://cloud.githubusercontent.com/assets/633088/7351631/60f6ba5a-ecd4-11e4-8371-a4e12f92a9fc.png)

**Comment by GUI** [comment]
The "contact us" URL can be customized, but it unfortunately wasn't documented until recently. I've submitted a pull request that changes the contact URL to this issue tracker (but you're certainly welcome to tweak this however you best see fit): https://github.com/nasa/api-docs/pull/35 I've also updated the snippet with the other recent optional settings we've added to better tailor this signup process.
