### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource. Does APOD allow CORS?

### ISSUE THREAD

**Issue by benjaminboruff** [nasa/api-docs#37]
It looks like https://api.data.gov/nasa/planetary/apod doesn't allow CORS? I can access it via my web browser just fine with my API_KEY, but not from my development web server running on localhost. Thus I get: 
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

 I'm just wondering if that can be changed - to allow CORS? I was hoping to avoid JSONP ... 
Thanks!
 -Ben
Benjamin H Boruff
benboruff@gmail.com
benjaminboruff.github.io

**Comment by knynkwl** [comment]
+1

**Comment by danhammer** [comment]
thanks.  I will work on this really soon -- this week?!  thanks for the note.

**Comment by AdamMurray** [comment]
+1

I would also really love to avoid jsonp

**Comment by wnodom** [comment]
+1

CORS support would definitely be appreciated.

**Comment by quicoto** [comment]
+1

**Comment by danhammer** [comment]
Thanks so much for the issues.  I am slowly working my way through them.  CORS support is now supported for the APOD API.  (I will now move on to the Landsat API to address #39.)  And I'll close this issue, once I update the documentation.  

There is also a new endpoint to allow CORS support for the image itself, rather than just the JSON response.  So, check it out: 

**QUERY**:

```bash
https://api.nasa.gov/planetary/apod?date=2015-06-03&api_key=DEMO_KEY
```

**RESONSE**:

```json
{
  "url": "http://apod.nasa.gov/apod/image/1506/hyperion02_cassini_960.jpg",
  "media_type": "image", 
  "explanation": "Why does this moon look like a sponge? To better investigate, NASA and ESA sent the Saturn-orbiting robotic spacecraft Cassini zooming past Saturn's moon Hyperion, once again, earlier this week.  One of the images beamed back to Earth is featured above, raw and unprocessed. Visible, as expected, are many unusually shaped craters with an unusual dark material at the bottom.  Although Hyperion spans about 250 kilometers, its small gravitational tug on Cassini indicates that it is mostly empty space and so has very low surface gravity.  Therefore, the odd shapes of many of Hyperion's craters are thought to result from impacts that primarily compress and eject surface material -- instead of the more typical round craters that appear after a circular shock wave that explosively redistributes surface material. Cassini is on track for another flyby of Saturn's Dione in about two weeks.   Retrospective: All Previous June 3 APODs",
  "concepts": null,
  "title": "Flyby Image of Saturns Sponge Moon Hyperion"
}
```
**HEADERS**:
```
accept-ranges:bytes
access-control-allow-origin:*
age:0
alternate-protocol:80:quic,p=0
cache-control:no-cache
Connection:keep-alive
content-encoding:gzip
Content-Length:662
Content-Type:application/json
Date:Wed, 03 Jun 2015 16:24:45 GMT
Server:nginx
vary:Accept-Encoding, Accept-Encoding
via:1.1 varnish-v4
x-cache:MISS
X-RateLimit-Limit:30
X-RateLimit-Remaining:24
x-varnish:15443927
```

If you want the image directly with CORS support, hit this new endpoint:

**QUERY**:

```bash
https://api.nasa.gov/planetary/apod/direct?date=2015-06-03&api_key=DEMO_KEY
```

**RESPONSE**:

![direct](https://cloud.githubusercontent.com/assets/428641/7966321/203fc4d6-09d8-11e5-9368-1a28de5a8c6d.png)


**HEADERS**:

```
accept-ranges:bytes
access-control-allow-origin:*
age:0
alternate-protocol:80:quic,p=0
cache-control:no-cache
Connection:keep-alive
Content-Length:538966
Content-Type:image/png
Date:Wed, 03 Jun 2015 17:03:18 GMT
Server:nginx
via:1.1 varnish-v4
x-cache:MISS
X-RateLimit-Limit:30
X-RateLimit-Remaining:21
x-varnish:15195289
```

More generally, there is a lot to do.  Caching, CI testing, etc.  I will systematically address the issues; and then I am going to solicit help!  The only reason why this isn't a totally open project is that there are internal credentials that I need to mask out before public release.  After I do that, it would be awesome to have some help or code reviews!

**Comment by wnodom** [comment]
Thanks so much, Dan! Can't wait to give it a try.

**Comment by AdamMurray** [comment]
Great work Dan! Once I stop being an idiot at JS I'll be using this thoroughly

**Comment by benjaminboruff** [comment]
Excellent! I was able to query/receive the APOD JSON string from my local test webserver that serves up an AngularJS test app. Sweet! I'm sure we will all help out with testing ... just light the beacons!
-Ben
Benjamin H Boruff
benboruff@gmail.com
benjaminboruff.github.io

**Comment by danhammer** [comment]
awesome!  thanks for the support @wnodom, @AdamMurray, and @benjaminboruff!  I am progressively adding features, trying desperately not to change the structure of the response (just adding to it).  The new Landsat endpoints are going to be sweet.

**Comment by brianthomas** [comment]
Closing issue as it looks solved (and, I'll note that CORS is enabled in Flask APOD-API)

**Comment by Huc91** [comment]
https://api.nasa.gov/planetary/apod/direct?[insert API key here]

Returns Error 500
I'm struggling with this and can't find no solution? How can I have Cors enabled apod images?

**Comment by Fieel** [comment]
Yup same error here. I thought this problem was solved years ago?

https://api.nasa.gov/planetary/apod/direct?date=2015-06-03&api_key=DEMO_KEY

returns

`{
  "code": 500, 
  "msg": "Sorry, unexpected error: must be str, not NotFound", 
  "service_version": "v1"
}`

**Comment by Huc91** [comment]
Yep, I don't know if it's a temporary problem because I stared using the API just a few days ago but it always returns:
> Internal Server Error
It would be very nice to have (again) CORS enabled images :-)

**Comment by Fieel** [comment]
@Huc91 i just created a new issue, feel free to report there

**Comment by jasonduley** [comment]
please try again

**Comment by Fieel** [comment]
@jasonduley as stated in https://github.com/nasa/api-docs/issues/99#issuecomment-384935929 the "direct" url is broken so i just used the normal URL and it's working. People (like me) might find this thread and waste a lot of time trying to use the 'direct' URL though.

**Comment by amygoodchild** [comment]
I'm having the same issue. The direct URL is broken and the other one doesn't allow me to use the image url in my code due to a CORS error. Any chance of getting this looked again? Thanks so much!
