### ISSUE TITLE
APOD query by attributes other than date.

### ISSUE THREAD

**Issue by gdomingu** [nasa/api-docs#47]
Hello, I absolutely love APOD and I was so happy to discover your API last week. I've been working on a ruby gem as a side project and was wondering if you have any plans to allow query by keywords?

That way you could send something like 
https://api.nasa.gov/planetary/apod?q=nebula&concept_tags=True&api_key=DEMO_KEY
And get back posts that have the word "nebula" in it. 

Thanks!

**Comment by brianthomas** [comment]
This isn't easily possible. We don't maintain a cache of prior APOD pages (and no current plan to do so), so we can only try to match text on the page for the indicated date. But this functionality is trivial for the client, we already pass the description field back in the JSON so you can test today's page this way.

**Comment by gdomingu** [comment]
Got it thanks!
