### ISSUE TITLE
API registration form doesn't work for me

### ISSUE THREAD

**Issue by j127** [nasa/api-docs#50]
When I submit the form on the [API registration form](http://api.nasa.gov/#contributing), it POSTs to `https://api.data.gov/api-umbrella/v1/users.json?api_key=SOME_KEY` with a _403 Forbidden_ error in response. Firefox 38.0.5 on Windows 8.1.

Screenshot:

![nasa_api_registration_error](https://cloud.githubusercontent.com/assets/96479/8298509/7c7b2254-191e-11e5-9440-977b910adfaa.png)

**Comment by j127** [comment]
Update: it did work for me in Chrome, Incognito mode (no plugins). I still get a 403 in Firefox.

**Comment by JustinGOSSES** [comment]
THis is an old problem and has been fixed.
