### ISSUE TITLE
example API query 404s

### ISSUE THREAD

**Issue by gbinal** [nasa/api-docs#52]
I just created an API key and the resulting page (and email that was sent to me) had an example API request just like this:  `https://api.nasa.gov/api.nasa.gov/nasa/planetary/apod?api_key=MY_API_KEY&format=JSON`.  But that returns a gh-pages 404.

**Comment by jasonduley** [comment]
fixed, thanks.

**Comment by gbinal** [comment]
Thanks, Jason!  

I believe that the example link in the email still 404's though - maybe because it's relative?  

I'm reopening the issue just in case.

**Comment by jasonduley** [comment]
yep, it was relative. I updated to absolute URL which I agree with you, is better.  Thanks.
