### ISSUE TITLE
Earth (Landsat) API Image Compiling

### ISSUE THREAD

**Issue by isaachinman** [nasa/api-docs#53]
I'm currently building a web app with the Earth (Landsat) API, and am frustrated at its limited functionality. The images are quite small (0.025° x 0.025°), so trying to grid out a map at any reasonable zoom level requires hundreds of requests.

It'd be quite easy to compile images server-side and then serve such compiled images. Off the top of my head, this could be done in PHP ([example](https://stackoverflow.com/questions/8858489/merge-two-images-in-php)).

The idea is that you would be able to send a request of bounds instead of a single lat/lon, like so:

```
[[northWestCorner],[northEastCorner],[southWestCorner],[southEastCorner]]
```

And the API would return a stitched png of all the 0.025° x 0.025° pngs within those bounds. This would drastically decrease the number of requests required to grid out a map.

**Comment by The-Penultimate-Defenestrator** [comment]
+1 for this

**Comment by isaachinman** [comment]
@The-Penultimate-Defenestrator 

Hey, it's been quite awhile since I've used the API. From what I recall, the image files themselves are a set size (delivered straight from the satellite), so any stitching or compiled tiles would have to be an additional feature.

**Comment by The-Penultimate-Defenestrator** [comment]
There is a `dim` argument, described as:

>width and height of the image in degrees

And the default is 0.025

**Comment by The-Penultimate-Defenestrator** [comment]
My Python stitching code:
```python
import urllib2
import json
import time
from io import BytesIO
from PIL import Image

URL="https://api.nasa.gov/planetary/earth/imagery?lon={}&lat={}&date={}&api_key={}"
API_KEY="ymjXp9qz2jJDR5tNEb0qa5YekynvAcVLJvKVcxYH"

def get_satellite_image(location=None,date=None):
	if location is None:
		location=(41.7475067,-74.0968971) #Coordinates of New Paltz
	if date is None:
		date=time.strftime("%Y-%m-%d")

	lat,lon=location

	req_url=URL.format(str(lon),str(lat),date,API_KEY)
	req=json.loads(urllib2.urlopen(req_url).read())

	image_url=req["url"]
	print "Image at "+image_url
	image = urllib2.urlopen(image_url)
	b=BytesIO(image.read())
	return b

def get_stitched_satellite_image(l=(41.7475067,-74.0968971),date=None):
	d=0.025
	coords = [l,#Original
				(l[0]+d,l[1]),(l[0],l[1]+d),(l[0]-d,l[1]),(l[0],l[1]-d),#Horizontally adjacent
				(l[0]+d,l[1]+d),(l[0]+d,l[1]-d),(l[0]-d,l[1]-d),(l[0]-d,l[1]+d)]#Diagonally adjacent
	
	coords.sort()
	image_files=[get_satellite_image(c,date) for c in coords]
	images=[Image.open(i) for i in image_files]
	imsize=512
	
	canvas=Image.new('RGB',(imsize*3,imsize*3))
	index=0
	for y in range(2,-1,-1):
		for x in range(3):
			coords=(x*imsize,y*imsize)
			canvas.paste(images[index],coords)
			index+=1		
	return canvas
	
def save_satellite_image(location=None,date=None,filename='out.png'):
	Image.open(get_satellite_image(location,date)).save(filename)

def save_stitched_satellite_image(location=(41.7475067,-74.0968971),date=None,filename='out.png'):
	get_stitched_satellite_image(location,date).save(filename)
		
if __name__ == "__main__":
	save_stitched_satellite_image((40.7,-74.0))
