### ISSUE TITLE
APOD: Only Content-Type and cache-control headers return non-Null values

### ISSUE THREAD

**Issue by benjaminboruff** [nasa/api-docs#54]
These are the headers the APOD API response are supposed to return, but I'm only getting the Content-Type and cache-control headers as non-Null values. Anyone else getting Null for the other header values? The X-RateLimit-Remaining is kind of important to know!

```
accept-ranges:bytes
access-control-allow-origin:*
age:0
alternate-protocol:80:quic,p=0
cache-control:no-cache
Connection:keep-alive
content-encoding:gzip
Content-Length:662
Content-Type:application/json
Date:Wed, 03 Jun 2015 16:24:45 GMT
Server:nginx
vary:Accept-Encoding, Accept-Encoding
via:1.1 varnish-v4
x-cache:MISS
X-RateLimit-Limit:30
X-RateLimit-Remaining:24
x-varnish:15443927
```

Don't we also need something like an access-control-expose-headers for the X-RateLimit-Remaining header on the server? (see section [5.3 Access-Control-Expose-Headers Response Header](http://www.w3.org/TR/cors/#simple-response-header) at w3.org). Or am I missing something?

**Comment by benjaminboruff** [comment]
FYI: Access-Control-Expose-Headers cannot accept a wildcard!

**Comment by brianthomas** [comment]
Hi, can you update on whether this is fixed in the refactored deployment?

**Comment by jnbetancourt** [comment]
Closing this issue. Feel free to re-open if the refactored deployment did not fix the problem.
