### ISSUE TITLE
APOD API documentation could use some updating.

### ISSUE THREAD

**Issue by Ricool06** [nasa/api-docs#57]
Dan has added new functionality to the APOD API such as ?hd and ?direct but the official API reference still only states that 3 parameters are available:

Parameter | Type | Default | Description
--- | --- | --- | ---
date | YYYY-MM-DD | today | The date of the APOD image to retrieve
concept_tags | bool | False | Return an ordered dictionary of concepts from the APOD explanation
api_key | string | DEMO_KEY | api.nasa.gov key for expanded usage

I have had first hand experience of the issue this causes by wrongly thinking a parameter doesn't exist, writing code for a workaround, only to realise the only place the parameter was mentioned was in the issues section.

Updated version (parameters that I know of.)

Parameter | Type | Default | Description
--- | --- | --- | ---
date | YYYY-MM-DD | today | The date of the APOD image to retrieve
concept_tags | bool | False | Return an ordered dictionary of concepts from the APOD explanation
api_key | string | DEMO_KEY | api.nasa.gov key for expanded usage
hd | boolean | False | Retrieve the URL for the high resolution image

Go to <code>https://api.nasa.gov/planetary/apod/direct(insert_api_call)</code> to retrieve the CORS enabled APOD image.

**Comment by jasonduley** [comment]
thanks @Ricool06 its been updated
