### ISSUE TITLE
CORS for neows?

### ISSUE THREAD

**Issue by milesthedisch** [nasa/api-docs#58]
Getting a cross origin error, when making a ajax request.

**Comment by Ricool06** [comment]
Use the CORS enabled image request.
[code]https://api.nasa.gov/planetary/apod/direct?api_key=DEMO_KEY[/code]
The "direct" part is the important bit.

**Comment by dgreenfield0** [comment]
Hey @milesthedisch, Thanks for letting us know about the issue. We just deployed an update to Neows that should allow cross-origin GET requests. Please let me know if you have any issues. 

Thanks,
Davidg

**Comment by milesthedisch** [comment]
Thanks David it works! Thanks for getting to it so fast! 

Feeling very cool cause im talking to a person that works at NASA!

Hey also a suggestion for the query parameters maybe add a parameter for size?

Also how did i asteroids that have already impacted earth?

**Comment by dgreenfield0** [comment]
Hey @milesthedisch, Glad to hear it's working again.
also to note, I actually don't work at NASA. My team and I built and maintain NeoWs, which is offered via NASA's api.  You can or tweet us at: https://twitter.com/SpaceRocksApps 

The query param suggestion is a great idea. Actually, we are working on adding the ability to search on specific attributes of an asteroid.

Thanks, 
Davidg

**Comment by dgreenfield0** [comment]
@jasonduley This issue can be closed.

Thanks, 
Davidg
