### ISSUE TITLE
Dim parameter broken

### ISSUE THREAD

**Issue by controversial** [nasa/api-docs#63]
In your Planetary Imagery API, the `dim` parameter is broken. I think your API does not convert it from the string (as it is in the URL) to an integer before dividing.

**Comment by lockwooddev** [comment]
It still is broken.

`https://api.nasa.gov/planetary/earth/imagery?lon=100.75&lat=1.5&date=2014-02-01&cloud_score=True&api_key=DEMO_KEY&dim=0.5`

`{"message": "Admins have been notified.", "error": "unsupported operand type(s) for /: 'unicode' and 'int'"}`

**Comment by rjbergerud** [comment]
Still broken +1

**Comment by JamesBedford** [comment]
Still broken, I guess this is an out-of-date resource. Perhaps we should be using GIBS instead?

[https://wiki.earthdata.nasa.gov/display/GIBS/GIBS+API+for+Developers](https://wiki.earthdata.nasa.gov/display/GIBS/GIBS+API+for+Developers)

**Comment by maodijim** [comment]
By today still borken

**Comment by jnbetancourt** [comment]
This issue has been fixed. Thank you for your patience!
