### ISSUE TITLE
HTTPS Image URLs

### ISSUE THREAD

**Issue by krlbaker** [nasa/api-docs#71]
Thank you for all the work you have done on this project. I absolutely love the APOD. I am looking to build an app that utilizes the APOD and one of the requirements is the image urls have to be secure with https:// paths. Would it be possible to make these available? I tried changing the link to secure but did not get a response from the host. 

Thank you!

**Comment by jasonduley** [comment]
unfortunately the backend site we are scraping this from only supports HTTP
