### ISSUE TITLE
404 links

### ISSUE THREAD

**Issue by jareis** [nasa/api-docs#73]
All links in the api-docs/source/index.md are returning 404

**Comment by jasonduley** [comment]
please try it again

**Comment by jareis** [comment]
Hello @jasonduley,

The problem still exists.

After comparing the info on the index.md with the info in https://api.nasa.gov/api.html I noticed, that the URL are not the same:

**URL on index.md:** https://api.data.gov/nasa/planetary/earth/imagery?lon=100.75&lat=1.5&date=2014-02-01&cloud_score=True&api_key=DEMO_KEY

**URL on api.nasa.gov:** https://api.nasa.gov/planetary/earth/imagery?lon=100.75&lat=1.5&date=2014-02-01&cloud_score=True&api_key=DEMO_KEY

**Comment by jasonduley** [comment]
I see.  The file index.md in master is no longer current.  I've just been maintaining the site in the staging branch.  please use the URL on api.nasa.gov
