### ISSUE TITLE
Enforce HTTP Strict Transport Security on api.nasa.gov

### ISSUE THREAD

**Issue by martinsuchan** [nasa/api-docs#74]
For better security and for preventing various Protocol Downgrade Attacks the endpoint **api.nasa.gov** should enforce **HTTP Strict Transport Security** - add response header indicating that all communication should always happen on HTTPS.
Since api.nasa.gov works already only on HTTPS, adding HSTS should not break anythng, only imrpove the security for all the clients.
For more details about HSTS please check this article:
https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security

**Comment by jnbetancourt** [comment]
NASA APIs now enforce strict transport security. Thanks for the suggestion!
