### ISSUE TITLE
Cannot Connect to APOD via HTTPS on Pre-Lollipop Android devices

### ISSUE THREAD

**Issue by JeffreyCA** [nasa/api-docs#80]
I am trying to connect to APOD resources such as https://apod.nasa.gov/apod/astropix.html on Android using OkHttp, but I keep getting an SSL Handshake error. This occurs on devices running Android versions earlier than 4.4.2.

I ran some tests on SSLLabs and here are the results: https://www.ssllabs.com/ssltest/analyze.html?d=apod.nasa.gov&s=129.164.179.22

Note all of the pre-4.4.2 devices result in a handshake failure.

NASA's other domains do not have this problem, all devices are able to handshake without any problems: https://www.ssllabs.com/ssltest/analyze.html?d=api.nasa.gov&s=34.193.234.42

I'm currently developing an Android application which uses APOD images and since the move to HTTPS, I've been getting handshake errors on certain Android devices as a result.

**Comment by brianthomas** [comment]
I just ran your tests from ssllabs and it ran OK for me ("Grade B" for both tests although I admit to having no idea what the grading system means..)

**Comment by jasonduley** [comment]
thanks @brianthomas 
we had to implement OMB Mandate M-15-13 https://https.cio.gov/guide/ and update all of our SSL configurations to the newest versions and this is most likely the cause of your client breaking

**Comment by JeffreyCA** [comment]
Hello, thanks for the response!

I totally forgot about this open issue, but I managed to solve this with a combination of [this](https://github.com/square/okhttp/issues/2372#issuecomment-244807676) and [this](https://developer.android.com/training/articles/security-gms-provider.html).
