### ISSUE TITLE
CORS is not enabled for Curiosity without a Demo API Key on Mars-Photos API

### ISSUE THREAD

**Issue by berraknil** [nasa/api-docs#83]
Hi, I'm currently making a web app using the Mars-Photos API, the problem is if I don't use a DEMO_KEY (which as you might guess only allows for a certain amount of calls) and use my specific dev key instead, I can only request information about Opportunity and Spirit rovers and Curiosity just gives me a __"No 'Access-Control-Allow-Origin' header is present on the requested resource."__ error.
![mars-photos-curiosity-error](https://cloud.githubusercontent.com/assets/6593585/24095700/5c1e15a6-0d6f-11e7-83d7-547e7dfa4657.jpg)

Was wondering if it's possible to check to see what might be going wrong with CORS regarding that?

ps. all three rovers work correctly when just fetching JSON but not when trying to get data via Promises (using React, Redux and Axios), Curiosity always gives a CORS error.

Thanks for your time :)

**Comment by jasonduley** [comment]
@chrisccerami please chime in on this one.  thanks.

**Comment by berraknil** [comment]
I would really love to have an update on this, at least a confirmation if this is from a server side CORS problem or not, since it's breaking the app I'm working on right now, rendering it useless. Thank you for your time.

@jasonduley thank you for the response.

**Comment by brianthomas** [comment]
AFAIK, nobody is actively developing this code. I would love to see it open sourced so that the community could contribute patches (I don’t have cycles to fix it either), but Software Release Authority folks are very slow. We are trying tho.

=]brian

**Comment by berraknil** [comment]
@brianthomas Thanks for the reply! I agree that it would be better if these APIs were open sourced and open to contributions. It just seems weird that the other two rover photos are reachable but Curiosity isn't via using a specific API Key,  Well, I guess I'm gonna have to stick to the demo key and hope I won't hit the limit since it's a demo concept for now.

**Comment by chrisccerami** [comment]
@brianthomas @berraknil I don't know what Brian is talking about. I am the maintainer of the API, and it IS open source. No one has ever contributed any patches, but that doesn't mean that people are not able to or that it is not open source. The repo is located here: https://github.com/chrisccerami/mars-photo-api/. I recommend you open an issue there and I can try to look into it when I get a chance.

**Comment by jasonduley** [comment]
correct.  @chrisccerami maintains this API as a citizen scientist project.  @brianthomas and I catalog a bunch more APIs and some of those do not have the source released nor are they actively supported.
