### ISSUE TITLE
APOD Android SSL Error

### ISSUE THREAD

**Issue by gabi579510** [nasa/api-docs#84]
I retreive this error if I make request from Android 4.4 with Retrofit
Error:SSL handshake aborted: ssl=0xb97c6460: I/O error during system call, Connection reset by peer

URL:https://api.nasa.gov/planetary/apod?api_key=.........

GET 
HEADERS:"Cache-Control: no-cache",
        "Accept: application/json”

Request{method=GET, url=https://api.nasa.gov/planetary/apod?api_key=......, tag=null}

Response: javax.net.ssl.SSLException: SSL handshake aborted: ssl=0xb982e4b0: I/O error during system call, Connection reset by peer
		 details Message SSL handshake aborted: ssl=0xb982e4b0: I/O error during system call, Connection reset by peer

**Comment by jasonduley** [comment]
we recently updated all secure traffic on api.nasa.gov to use HSTS (latest).  Please ensure your clients can support this.  https://https.cio.gov/guide/

**Comment by gabi579510** [comment]
jasonduley can you suggest me an solution for this problem ! I'm trying to set this in headers but nothing Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"

**Comment by martinsuchan** [comment]
I've noticed that the apod.nasa.gov now uses SSL settings that is [compatible only with very recent devices](https://www.ssllabs.com/ssltest/analyze.html?d=api.nasa.gov&s=34.197.165.36). It supports only TLS 1.2 and ECDHE_RSA_WITH_AES cipher suites.  
It might be useful to supprt older devices as well - [see this article from Mozilla](https://wiki.mozilla.org/Security/Server_Side_TLS). The **Modern configuration** should fix the issue for older Android devices.  
Note HSTS configuration is independent of cipher suite configuration.

**Comment by gabi579510** [comment]
Thank you! Everything it's working fine!

**Comment by martinsuchan** [comment]
Just an update, in order to support older Android devices the backend needs to support TLS 1.0 side by side with TLS 1.2. TLS 1.0 is still secure, so no need to worry.
