### ISSUE TITLE
APOD Video not displaying

### ISSUE THREAD

**Issue by billwagner3** [nasa/api-docs#87]
Hi guys,
I have a page that you can click through the past APOD's, which works fine until a video comes up (for instance here in July, July 4th is a video) but the video does not display in Chrome, Firefox or Explorer, and when you try and click past to the next earlier date, you get a the data but not the pic to go along with it. Here's rough page with the apod: http://billwagner3.webfactional.com/nasa. Nasa.txt is my  js file for this project. I'm using Symfony framework, and nasatwig.txt is my html.twig file. 

There are no error messages being displayed in the console or network tabs in the browser. Browser thinks that the vid's been loaded, all with 200 codes from youtube. 

I've searched hi and lo on the internet for solutions to this and have found none. 

[nasatwig.txt](https://github.com/nasa/api-docs/files/1146349/nasatwig.txt)
[nasa.txt](https://github.com/nasa/api-docs/files/1146328/nasa.txt)

**Comment by brianthomas** [comment]
Hi Bill,

Its hard for me to troubleshoot this. I went to APOD site for July 4th and video played for me. Can you supply a link which demonstrates the error?

-brian

**Comment by billwagner3** [comment]
The link is in my text: http://billwagner3.webfactional.com/nasa.

Did you go to that link above? I tried on different computers and got the
same result.

By the by, I am working in Linux for the dev of this page. I have tried to
view on a Windows 7 machine as well as Windows 10 using chrome on both.

Go to the link and hit the back arrow to get to July 4.

**Comment by brianthomas** [comment]
Looks like the return payload is returning the youtube url with the correct url for the request. Without looking at your code, it would appear to me that the problem is that you aren’t embedding it in your page (perhaps you are always expecting hdurl parameter which is missing for this date?)

-brian

**Comment by billwagner3** [comment]
The code comes straight off the Nasa website. It doesn't work properly. I
put in my html page exactly what it says to do. Here's the page:
https://api.nasa.gov/#live_example

If you looked at my code, you'd see the same exact thing.

So, this hdurl is not mentioned. Is there a css attribute I could use? I am
not familiar with this. Please enlighten me. Thanks.

**Comment by jasonduley** [comment]
try making your video div element an iframe or straight up use a video tag in it's place

**Comment by billwagner3** [comment]
I've tried both of those to no avail. I've spent quite a bit of time on
this and have tried a lot of different things in a myriad of combinations.
I can get the video to actually work if I manually put in the date in the
api call, but then I"ve got a hard-coded date that doesn't change. It
doesn't work when cycling thru the pics of the day. Thanks for your time.

Bill

**Comment by jasonduley** [comment]
i just made a bin and it seems to load the video
https://jsbin.com/dadovilaza/1/edit?html,js,output
it must have something to do with initializing it once the page has loaded.  hmmm

**Comment by billwagner3** [comment]
Yeah, with a hardcode in the api call it works fine. I am stumped.

**Comment by jasonduley** [comment]
![image](https://user-images.githubusercontent.com/6842640/28186063-96d347fc-67ce-11e7-9563-c3b9a5089dc9.png)

**Comment by jasonduley** [comment]
saw this in the console when the date reached july 4th.

**Comment by billwagner3** [comment]
Ok. That's the first time I've seen that. I don't get that message when I
run it, it comes back clean, except no video. So, now I'm even more
confused. Lord.

**Comment by jasonduley** [comment]
what browser are you using?  perhaps there is an ad blocker working, try disabling it and see if that helps

**Comment by billwagner3** [comment]
I have been using both chrome and firefox on a Linux system. I've checked
for ad blockers and the such on both systems-- interesting that I am
getting the same exact problem no matter what browser I am using-- or
computer for that matter, I've checked the site on Windows 7 and 10 systems
using chrome and Explorer. No difference. I mean-- if you can't see it
either on my site, then it's not my browsers.

**Comment by jasonduley** [comment]
i c.  it was an issue on my end.  can you confirm the css "display" param is getting properly set to block.  it seems when I load 7-4-2017 and inspect, the element is styled to display none.

**Comment by billwagner3** [comment]
I'll be damned, that worked! There was no css display param set (it was
exactly as it is on the Nasa site). I did the same for the pics, since it
was not displaying when you went earlier to July 3. Now it all works.
Should be added to the example on the Nasa site.

Thanks Jason! :)

Bill

**Comment by jasonduley** [comment]
the nasa snippet did not need that explicitly set as it was loading images/vids at page load.  due to the runtime loading as your script was doing, the iframe got confused and it required this.  glad it is working now.

**Comment by billwagner3** [comment]
Thanks for the insight Jason. Good to know.
