### ISSUE TITLE
APOD API returning 502 Bad Gateway

### ISSUE THREAD

**Issue by NickIliev** [nasa/api-docs#89]
Making an API call even with the DEMO_KEY is returing 502 Bad Gateway

steps to reproduce:
execute
```
https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY
```

result:
```
Response with status: 502 Bad Gateway for URL: https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY
```

Using registered API key is resulting in the same status.

**Comment by sach2211** [comment]
Same issue happening with valid API key as well.

**Comment by jasonduley** [comment]
it's been fixed!  sorry about that
