### ISSUE TITLE
Look into embedded Plunkr/JSFiddle into API pages

### ISSUE THREAD

**Issue by jasonduley** [nasa/api-docs#9]

**Comment by danhammer** [comment]
It seems like there are ways to insert HTML directly into markdown, but i am totally open to just edit the HTML.

**Comment by jasonduley** [comment]
I'll create another ticket for your comment above.

**Comment by jasonduley** [comment]
here is an example: http://jsbin.com/help/how-can-i-embed-jsbin

use something similar to add a working test client for APIs on the page
