### ISSUE TITLE
Earth Imagery API call failing

### ISSUE THREAD

**Issue by chrislblake** [nasa/api-docs#94]
Hello,

I've been attempting to make calls from the https://api.nasa.gov/planetary/earth/imagery API, and they've been failing with the error message:

{"message": "Admins have been notified.", "error": "'Image' object has no attribute 'rgbtohsv'"}

This error has occurred with the calls from my API key, as well as the example given on the docs.

Does anyone know a way to fix or bypass this? I've tried appending 'rgbtohsv=true' to the query string in hopes that might fix the issue, but no luck.

Thanks.

**Comment by jnbetancourt** [comment]
This was caused by an update to one of the libraries that the API uses. We've deployed a change to fix this, and the calls should work now.
