### ISSUE TITLE
Orbital Uncertainty

### ISSUE THREAD

**Issue by jagoosw** [nasa/api-docs#95]
NeoWs API a value is returned called Orbital Uncertainty, on the Small Body Database website an uncertainty is given for each element not an overall number, also the number seems to be an integer.

What does the value called Orbital Uncertainty represent?

(I'm not sure this is an appropriate place to ask but I've emailed the contact on the website and haven't got a reply so couldn't think where else to ask)

**Comment by jagoosw** [comment]
I have found it, it is called a MPC uncertainty parameter as described here https://minorplanetcenter.net/iau/info/UValue.html

**Comment by dgreenfield0** [comment]
Hey @jagoosw, 
Sorry I didn't see your emails or this post.  Glad you found the info.

Feel free to ping me with other questions.

Thanks,
davidg

**Comment by jagoosw** [comment]
No worries, thanks!
